### ISSUE TITLE
Dockerimage

### ISSUE THREAD

**Issue by JakobMiksch** [pblottiere/QSA#4]
It would be useful to have a Dockerimage to deploy QSA in a microservice environment like a docker compose setup.

Possible example:

```yaml
version: "3.8"
services:
   qwa:
      image: qwa/qwa
      enviroment:
         - ENV_VAR_1=foo
         - ENV_VAR_2=bar
         - ENV_VAR_3=foobar
      volumes:
         - path/on/host/qsa.yml:/path/on/image/qsa.yml 
```

Ideas to consider:
- image must of course contain pyqgis, however it would be ideal to keep the image small
- is a config file really needed? maybe be all configs could also be written as envvars which would make a QSA deployment with Docker easier
