### ISSUE TITLE
Accessing QGIS projects stored in a Postgres database

### ISSUE THREAD

**Issue by JakobMiksch** [pblottiere/QSA#5]
QGIS Projects are often stored in a PostGIS database. That's why it would be great if QSA could access them as well.
a possible config file could look like:

```yaml
qgisserver:
    url: "http://qgisserver/ogc/"
    projects: "postgresql://username:password@host:port/dbname"  # PostgresSQL connection string
```

The table where the QGIS projects live must be called `qgis_projects` and can exist in multiple schemas. This means to reference a QGIS project one must provide the name of the project and also its schema.

The current way to call a project would not work anymore:

- current way to call a project: `[GET] /api/projects/<project_name>/layers`
- possible ways for project in different Postgres schemas:
  -  via query param: `[GET] /api/projects/<project_name>/layers?schema=<schema_name>` (default should be `public`)
  - add a new param in the URL:  `[GET] /api/<schema_name>/projects/<project_name>/layers` but this would interfere with the current way of the API ...
